### ISSUE TITLE
tf.variable with initial value does not work in eager mode

### ISSUE THREAD

**Issue by rnett** [tensorflow/java#155]
As the title says, `tf.variable` with an initial value does not work in eager mode.  I'm not sure if it is supposed to, as `tf.Variable` does in the python api but apparently didn't at first.  Interestingly, it's not the variable op that fails, it's the assign:
```java
cannot compute Assign as input #0(zero-based) was expected to be a int32_ref tensor but is a int32 tensor
org.tensorflow.exceptions.TFInvalidArgumentException: cannot compute Assign as input #0(zero-based) was expected to be a int32_ref tensor but is a int32 tensor
	at org.tensorflow.internal.c_api.AbstractTF_Status.throwExceptionIfNotOK(AbstractTF_Status.java:87)
	at org.tensorflow.EagerOperationBuilder.execute(EagerOperationBuilder.java:273)
	at org.tensorflow.EagerOperationBuilder.build(EagerOperationBuilder.java:66)
	at org.tensorflow.EagerOperationBuilder.build(EagerOperationBuilder.java:55)
	at org.tensorflow.op.core.Assign.create(Assign.java:97)
	at org.tensorflow.op.core.Helpers.createVariableWithInit(Helpers.java:51)
	at org.tensorflow.op.Ops.variable(Ops.java:7520)
```

**Comment by Craigacp** [comment]
Yeah, that's documented in the javadoc (https://github.com/tensorflow/java/blob/8c67a5a6eb6df9a671b5d7c3be674176b550bed2/tensorflow-core/tensorflow-core-api/src/main/java/org/tensorflow/op/core/Helpers.java#L40) for it as I didn't figure out an alternative at the time. We should at minimum fix it so it throws a sensible looking exception.

**Comment by rnett** [comment]
Could be done easily enough as part of #154, that's what I was originally going to suggest before I realized it was supported in python eager mode.

I assume the codegen doesn't support custom javadocs on the ops methods (for putting the warning on `tf.variable`)?
