### ISSUE TITLE
LSTM model not working

### ISSUE THREAD

**Issue by kyleboyle** [tensorflow/java#175]
I'm trying to make a prediction using the java 0.2.0 library on a lstm model created in python, but I'm getting an exception:
```
 org.tensorflow.exceptions.TFInvalidArgumentException: {{function_node __inference_standard_lstm_129848_specialized_for_StatefulPartitionedCall_StatefulPartitionedCall_sequential_lstm_PartitionedCall_at_tf_graph}} {{function_node __inference_standard_lstm_129848_specialized_for_StatefulPartitionedCall_StatefulPartitionedCall_sequential_lstm_PartitionedCall_at_tf_graph}} transpose expects a vector of size 2. But input(1) is a vector of size 3
                    [[{{node transpose}}]]
	 [[StatefulPartitionedCall/StatefulPartitionedCall/sequential/lstm/PartitionedCall]]
```

Created model in python 3.7 with tf 2.3 on macos.

model signature:

```
MetaGraphDef with tag-set: 'serve' contains the following SignatureDefs:

signature_def['__saved_model_init_op']:
  The given SavedModel SignatureDef contains the following input(s):
  The given SavedModel SignatureDef contains the following output(s):
    outputs['__saved_model_init_op'] tensor_info:
        dtype: DT_INVALID
        shape: unknown_rank
        name: NoOp
  Method name is:

signature_def['serving_default']:
  The given SavedModel SignatureDef contains the following input(s):
    inputs['lstm_input'] tensor_info:
        dtype: DT_FLOAT
        shape: (-1, 4, 14)
        name: serving_default_lstm_input:0
  The given SavedModel SignatureDef contains the following output(s):
    outputs['dense'] tensor_info:
        dtype: DT_FLOAT
        shape: (-1, 24)
        name: StatefulPartitionedCall:0
  Method name is: tensorflow/serving/predict

Defined Functions:
  Function Name: '__call__'
    Option #1
      Callable with:
        Argument #1
          inputs: TensorSpec(shape=(None, 4, 14), dtype=tf.float32, name='inputs')
        Argument #2
          DType: bool
          Value: True
        Argument #3
          DType: NoneType
          Value: None
    Option #2
      Callable with:
        Argument #1
          lstm_input: TensorSpec(shape=(None, 4, 14), dtype=tf.float32, name='lstm_input')
        Argument #2
          DType: bool
          Value: True
        Argument #3
          DType: NoneType
          Value: None
    Option #3
      Callable with:
        Argument #1
          inputs: TensorSpec(shape=(None, 4, 14), dtype=tf.float32, name='inputs')
        Argument #2
          DType: bool
          Value: False
        Argument #3
          DType: NoneType
          Value: None
    Option #4
      Callable with:
        Argument #1
          lstm_input: TensorSpec(shape=(None, 4, 14), dtype=tf.float32, name='lstm_input')
        Argument #2
          DType: bool
          Value: False
        Argument #3
          DType: NoneType
          Value: None

  Function Name: '_default_save_signature'
    Option #1
      Callable with:
        Argument #1
          lstm_input: TensorSpec(shape=(None, 4, 14), dtype=tf.float32, name='lstm_input')

  Function Name: 'call_and_return_all_conditional_losses'
    Option #1
      Callable with:
        Argument #1
          lstm_input: TensorSpec(shape=(None, 4, 14), dtype=tf.float32, name='lstm_input')
        Argument #2
          DType: bool
          Value: True
        Argument #3
          DType: NoneType
          Value: None
    Option #2
      Callable with:
        Argument #1
          inputs: TensorSpec(shape=(None, 4, 14), dtype=tf.float32, name='inputs')
        Argument #2
          DType: bool
          Value: True
        Argument #3
          DType: NoneType
          Value: None
    Option #3
      Callable with:
        Argument #1
          inputs: TensorSpec(shape=(None, 4, 14), dtype=tf.float32, name='inputs')
        Argument #2
          DType: bool
          Value: False
        Argument #3
          DType: NoneType
          Value: None
    Option #4
      Callable with:
        Argument #1
          lstm_input: TensorSpec(shape=(None, 4, 14), dtype=tf.float32, name='lstm_input')
        Argument #2
          DType: bool
          Value: False
        Argument #3
          DType: NoneType
          Value: None
```
Java code which is requesting the outputs:

```java
        try (SavedModelBundle bundle = SavedModelBundle.load(this.savedModel.getAbsolutePath(), "serve")) {

            String inputName = "serving_default_lstm_input:0";
            String outputName = "StatefulPartitionedCall:0";

            Tensor<TFloat32> inputTensor = TFloat32.tensorOf(Shape.of(4, 14));
            // predictionTensorData = float[4][14]
            StdArrays.copyTo(predictionTensorData, inputTensor.data());

            try (Session s = bundle.session()) {
                Tensor<?> result = s.runner().feed(inputName, inputTensor).fetch(outputName).run().get(0);
                System.out.println(result.shape());
            }
        }
```
```
{{function_node __inference_standard_lstm_129848_specialized_for_StatefulPartitionedCall_StatefulPartitionedCall_sequential_lstm_PartitionedCall_at_tf_graph}} {{function_node __inference_standard_lstm_129848_specialized_for_StatefulPartitionedCall_StatefulPartitionedCall_sequential_lstm_PartitionedCall_at_tf_graph}} transpose expects a vector of size 2. But input(1) is a vector of size 3
	 [[{{node transpose}}]]
	 [[StatefulPartitionedCall/StatefulPartitionedCall/sequential/lstm/PartitionedCall]]
org.tensorflow.exceptions.TFInvalidArgumentException: {{function_node __inference_standard_lstm_129848_specialized_for_StatefulPartitionedCall_StatefulPartitionedCall_sequential_lstm_PartitionedCall_at_tf_graph}} {{function_node __inference_standard_lstm_129848_specialized_for_StatefulPartitionedCall_StatefulPartitionedCall_sequential_lstm_PartitionedCall_at_tf_graph}} transpose expects a vector of size 2. But input(1) is a vector of size 3
	 [[{{node transpose}}]]
	 [[StatefulPartitionedCall/StatefulPartitionedCall/sequential/lstm/PartitionedCall]]
	at org.tensorflow.internal.c_api.AbstractTF_Status.throwExceptionIfNotOK(AbstractTF_Status.java:87) ~[tensorflow-core-api-0.2.0.jar:?]
	at org.tensorflow.Session.run(Session.java:666) ~[tensorflow-core-api-0.2.0.jar:?]
	at org.tensorflow.Session.access$100(Session.java:72) ~[tensorflow-core-api-0.2.0.jar:?]
	at org.tensorflow.Session$Runner.runHelper(Session.java:381) ~[tensorflow-core-api-0.2.0.jar:?]
	at org.tensorflow.Session$Runner.run(Session.java:329) ~[tensorflow-core-api-0.2.0.jar:?]
```
Thanks for any insight.

**Comment by Craigacp** [comment]
Could you share with us the Python code that created the LSTM? Or the model file itself?

**Comment by kyleboyle** [comment]
Sure. Here is the model dir. I can't share the code that created it. I can use it in python to make predictions, forgot to mention that.
[2020-12-24T14-27-23_2020-11-10T00-00-00_2020-11-11T00-00-00.zip](https://github.com/tensorflow/java/files/5745090/2020-12-24T14-27-23_2020-11-10T00-00-00_2020-11-11T00-00-00.zip)

**Comment by kyleboyle** [comment]
I get the same error when running on deprecated java lib as well:

```
[_Derived_]{{function_node __inference_standard_lstm_129848_specialized_for_StatefulPartitionedCall_StatefulPartitionedCall_sequential_lstm_PartitionedCall_at_tf_graph}} {{function_node __inference_standard_lstm_129848_specialized_for_StatefulPartitionedCall_StatefulPartitionedCall_sequential_lstm_PartitionedCall_at_tf_graph}} transpose expects a vector of size 2. But input(1) is a vector of size 3
	 [[{{node transpose}}]]
	 [[StatefulPartitionedCall/StatefulPartitionedCall/sequential/lstm/PartitionedCall]]
java.lang.IllegalArgumentException: [_Derived_]{{function_node __inference_standard_lstm_129848_specialized_for_StatefulPartitionedCall_StatefulPartitionedCall_sequential_lstm_PartitionedCall_at_tf_graph}} {{function_node __inference_standard_lstm_129848_specialized_for_StatefulPartitionedCall_StatefulPartitionedCall_sequential_lstm_PartitionedCall_at_tf_graph}} transpose expects a vector of size 2. But input(1) is a vector of size 3
	 [[{{node transpose}}]]
	 [[StatefulPartitionedCall/StatefulPartitionedCall/sequential/lstm/PartitionedCall]]
	at org.tensorflow.Session.run(Native Method) ~[libtensorflow-1.15.0.jar:1.15.0]
	at org.tensorflow.Session.access$100(Session.java:48) ~[libtensorflow-1.15.0.jar:1.15.0]
	at org.tensorflow.Session$Runner.runHelper(Session.java:326) ~[libtensorflow-1.15.0.jar:1.15.0]
	at org.tensorflow.Session$Runner.run(Session.java:276) ~[libtensorflow-1.15.0.jar:1.15.0]
```

I'm not sure how I'm suppose to work with multi dimensional arrays with this interface so i just flattened the array to try it out:
```java
String inputName = "serving_default_lstm_input:0";
            String outputName = "StatefulPartitionedCall:0";
            Session sess = bundle.session();
            Tensor x = Tensor.create(new long[] { 4, 14 }, FloatBuffer.wrap(flatten(predictionTensorData)));
            float[] y = sess.runner().feed(inputName, x).fetch(outputName).run().get(0).copyTo(new float[24]);
            // print out the result.
            System.out.println(y[0]);
```
