### ISSUE TITLE
Unintuitive out of memory errors, and odd OOMs

### ISSUE THREAD

**Issue by rnett** [tensorflow/java#186]
I'm experimenting with `TensorScope`, and thus using large amounts of memory for tensors.  However, when I try this, I get odd oom-related errors.

Example (kotlin):
```kotlin
repeat(1000) {
    TFloat32.tensorOf(Shape.of(10000, 10000))
}
```
gives
```
2021-01-11 20:36:45.599992: W external/org_tensorflow/tensorflow/core/framework/cpu_allocator_impl.cc:81] Allocation of 400000000 exceeds 10% of free system memory.
2021-01-11 20:36:45.625897: W external/org_tensorflow/tensorflow/core/framework/cpu_allocator_impl.cc:81] Allocation of 400000000 exceeds 10% of free system memory.
2021-01-11 20:36:45.626092: W external/org_tensorflow/tensorflow/core/framework/cpu_allocator_impl.cc:81] Allocation of 400000000 exceeds 10% of free system memory.
2021-01-11 20:36:45.626180: W external/org_tensorflow/tensorflow/core/framework/cpu_allocator_impl.cc:81] Allocation of 400000000 exceeds 10% of free system memory.
2021-01-11 20:36:45.626262: W external/org_tensorflow/tensorflow/core/framework/cpu_allocator_impl.cc:81] Allocation of 400000000 exceeds 10% of free system memory.
Exception in thread "main" java.lang.NullPointerException
	at org.tensorflow.internal.buffer.TensorBuffers.tensorMemory(TensorBuffers.java:180)
	at org.tensorflow.internal.buffer.TensorBuffers.toFloats(TensorBuffers.java:102)
	at org.tensorflow.internal.types.TFloat32Mapper.mapDense(TFloat32Mapper.java:34)
	at org.tensorflow.internal.types.TFloat32Mapper.mapDense(TFloat32Mapper.java:30)
	at org.tensorflow.RawTensor.asTypedTensor(RawTensor.java:215)
	at org.tensorflow.Tensor.of(Tensor.java:90)
	at org.tensorflow.Tensor.of(Tensor.java:63)
	at org.tensorflow.types.TFloat32.tensorOf(TFloat32.java:79)
	at tester.TensorScopeKt.main(TensorScope.kt:8)
	at tester.TensorScopeKt.main(TensorScope.kt)
```

I'd think this is a fairly straight forward OOM, just without nice error messages, but the used memory in Task Manager (I'm on Windows) barely moves.  I do start using heap memory, but it caps 100MB, even with `-Xmx6g`.  Is there some limit on tensor allocations I'm not aware of?

**Comment by saudet** [comment]
Allocating virtual memory doesn't make the OS allocate any physical memory.
If you'd like to have both coincide a bit more, initialize all the memory to some value like `0`.

**Comment by rnett** [comment]
This differes from if I run something like:
```kotlin
Graph().use { graph ->
    val tf = Ops.create(graph)
    val out = tf.zeros(tf.array(100_000, 100_000), TFloat32::class.java)

    Session(graph).use{ sess ->
        val tensors = mutableListOf<TFloat32>()
        repeat(1000){
            println("$it")
            val t = sess.runner().fetch(out).run()[0] as TFloat32
            tensors += t
            delay(10)
        }
    }

}
```

Which I see in Task Manager and doesn't run out of memory.

**Comment by rnett** [comment]
That would explain the difference.  Is the NPE from running out of virtual memory?

**Comment by saudet** [comment]
Most likely, yes: "Memory type: Paged pool  | Limit in 64-bit Windows: 384 GB or system commit limit"
https://docs.microsoft.com/en-us/windows/win32/memory/memory-limits-for-windows-releases
