### ISSUE TITLE
Warning: Could not load Loader: java.lang.UnsatisfiedLinkError: no jnijavacpp in java.library.path

### ISSUE THREAD

**Issue by micosacak** [tensorflow/java#259]
Thanks I will use it. But now I have problem with loading saved models (tensforflow version 2.4.1 in Python) or shall I open a new issue?

´SavedModelBundle theModel = SavedModelBundle.load("/model", "serve");´

Loading this model by tensorflow 1.15.0 works, but does not work if I use tensorflow-core-api.

I found a simialr issue; (https://github.com/bytedeco/javacpp-presets/issues/396)

`Warning: Could not load Loader: java.lang.UnsatisfiedLinkError: no jnijavacpp in java.library.path: C:\Users\cosacak.p2\pool\plugins\org.eclipse.justj.openjdk.hotspot.jre.full.win32.x86_64_15.0.2.v20210201-0955\jre\bin;C:\Windows\Sun\Java\bin;C:\Windows\system32;C:\Windows;C:/Users/cosacak/.p2/pool/plugins/org.eclipse.justj.openjdk.hotspot.jre.full.win32.x86_64_15.0.2.v20210201-0955/jre/bin/server;C:/Users/cosacak/.p2/pool/plugins/org.eclipse.justj.openjdk.hotspot.jre.full.win32.x86_64_15.0.2.v20210201-0955/jre/bin;C:\ActiveTcl\bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Perl64\site\bin;C:\Perl64\bin;

--- curated ---

C:\Users\cosacak\AppData\Local\Programs\Python\Python39;C:\Program Files\MySQL\MySQL Shell 8.0\bin;C:\Program Files\Java\jre1.8.0_221\bin;C:\Users\cosacak\eclipse\java-2020-12\eclipse;;.
at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2447)
at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:809)
at java.base/java.lang.System.loadLibrary(System.java:1893)
at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1683)
at org.bytedeco.javacpp.Loader.load(Loader.java:1300)
at org.bytedeco.javacpp.Loader.load(Loader.java:1123)
at org.tensorflow.internal.c_api.global.tensorflow.(tensorflow.java:12)
at java.base/java.lang.Class.forName0(Native Method)
at java.base/java.lang.Class.forName(Class.java:468)
at org.bytedeco.javacpp.Loader.load(Loader.java:1190)
at org.bytedeco.javacpp.Loader.load(Loader.java:1139)
at org.tensorflow.NativeLibrary.load(NativeLibrary.java:48)
at org.tensorflow.TensorFlow.init(TensorFlow.java:111)
at org.tensorflow.TensorFlow.(TensorFlow.java:126)
at org.tensorflow.SavedModelBundle.(SavedModelBundle.java:438)
at TfDataTypeIssue.main(TfDataTypeIssue.java:27)
Caused by: java.lang.UnsatisfiedLinkError: no tensorflow_cc in java.library.path: C:\Users\cosacak.p2\pool\plugins\org.eclipse.justj.openjdk.hotspot.jre.full.win32.x86_64_15.0.2.v20210201-0955\jre\bin;

--- curated ---

C:\Users\cosacak\AppData\Local\Programs\Python\Python39;C:\Users\cosacak\AppData\Local\Programs\Python\Python36\Scripts;C:\Users\cosacak\AppData\Local\Programs\Python\Python39;C:\Program Files\MySQL\MySQL Shell 8.0\bin;C:\Program Files\Java\jre1.8.0_221\bin;C:\Users\cosacak\eclipse\java-2020-12\eclipse;;.
at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2447)
at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:809)
at java.base/java.lang.System.loadLibrary(System.java:1893)
at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1683)
at org.bytedeco.javacpp.Loader.load(Loader.java:1227)
... 11 more`

**Comment by micosacak** [comment]
the solution was to use `tensorflow-core-platform`

`<dependency>
  <groupId>org.tensorflow</groupId>
  <artifactId>tensorflow-core-platform</artifactId>
  <version>0.3.1</version>
</dependency>`
