### ISSUE TITLE
org.tensorflow.exceptions.TFInvalidArgumentException: ConcatOp : Expected concatenating dimensions in the range [-1, 1), but got 1

### ISSUE THREAD

**Issue by JWenBin** [tensorflow/java#269]
When I try to run my model like this:
```
val z = session.runner()
      .feed("serving_default_afid_index", id_index)
      .feed("serving_default_ageLV", ageLV)
      .feed("serving_default_city", city)
// other feed ......
      .fetch("StatefulPartitionedCall:0")
      .run()
      .get(0)
```
I get this error message:
```
org.tensorflow.exceptions.TFInvalidArgumentException: ConcatOp : Expected concatenating dimensions in the range [-1, 1), but got 1
	 [[{{node model/concatenate_4/concat}}]]
	at org.tensorflow.internal.c_api.AbstractTF_Status.throwExceptionIfNotOK(AbstractTF_Status.java:87)
	at org.tensorflow.Session.run(Session.java:691)
	at org.tensorflow.Session.access$100(Session.java:72)
	at org.tensorflow.Session$Runner.runHelper(Session.java:381)
	at org.tensorflow.Session$Runner.run(Session.java:329)
```

Thanks!

**Comment by JWenBin** [comment]
Model: "model"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
==================================================================================================
afid_index (InputLayer)         [(None, 1)]          0                                            
__________________________________________________________________________________________________
itemId_index (InputLayer)       [(None, 1)]          0                                            
__________________________________________________________________________________________________
singerid_index (InputLayer)     [(None, 1)]          0                                            
__________________________________________________________________________________________________
singerCountry_index (InputLayer [(None, 1)]          0                                            
__________________________________________________________________________________________________
currentCountry (InputLayer)     [(None, 1)]          0                                            
__________________________________________________________________________________________________
ageLV (InputLayer)              [(None, 1)]          0                                            
__________________________________________________________________________________________________
sex (InputLayer)                [(None, 1)]          0                                            
__________________________________________________________________________________________________
city (InputLayer)               [(None, 1)]          0                                            
__________________________________________________________________________________________________
curclientversioncode (InputLaye [(None, 1)]          0                                            
__________________________________________________________________________________________________
lastua (InputLayer)             [(None, 1)]          0                                            
__________________________________________________________________________________________________
phonecountrycode (InputLayer)   [(None, 1)]          0                                            
__________________________________________________________________________________________________
item_pop (InputLayer)           [(None, 1)]          0                                            
__________________________________________________________________________________________________
singerLocalPop (InputLayer)     [(None, 1)]          0                                            
__________________________________________________________________________________________________
singerGlobalPop (InputLayer)    [(None, 1)]          0                                            
__________________________________________________________________________________________________
publicDays (InputLayer)         [(None, 1)]          0                                            
__________________________________________________________________________________________________
sparse_emb_afid_index (Embeddin (None, 1, 4)         4960        afid_index[0][0]                 
__________________________________________________________________________________________________
sparse_emb_itemId_index (Embedd (None, 1, 4)         71696       itemId_index[0][0]               
__________________________________________________________________________________________________
sparse_emb_singerid_index (Embe (None, 1, 4)         16100       singerid_index[0][0]             
__________________________________________________________________________________________________
sparse_emb_singerCountry_index  (None, 1, 4)         444         singerCountry_index[0][0]        
__________________________________________________________________________________________________
sparse_emb_currentCountry (Embe (None, 1, 4)         96          currentCountry[0][0]             
__________________________________________________________________________________________________
sparse_emb_ageLV (Embedding)    (None, 1, 4)         48          ageLV[0][0]                      
__________________________________________________________________________________________________
sparse_emb_sex (Embedding)      (None, 1, 4)         12          sex[0][0]                        
__________________________________________________________________________________________________
sparse_emb_city (Embedding)     (None, 1, 4)         312         city[0][0]                       
__________________________________________________________________________________________________
sparse_emb_curclientversioncode (None, 1, 4)         404         curclientversioncode[0][0]       
__________________________________________________________________________________________________
sparse_emb_lastua (Embedding)   (None, 1, 4)         1644        lastua[0][0]                     
__________________________________________________________________________________________________
sparse_emb_phonecountrycode (Em (None, 1, 4)         72          phonecountrycode[0][0]           
__________________________________________________________________________________________________
no_mask_4 (NoMask)              (None, 1, 4)         0           sparse_emb_afid_index[0][0]      
                                                                 sparse_emb_itemId_index[0][0]    
                                                                 sparse_emb_singerid_index[0][0]  
                                                                 sparse_emb_singerCountry_index[0]
                                                                 sparse_emb_currentCountry[0][0]  
                                                                 sparse_emb_ageLV[0][0]           
                                                                 sparse_emb_sex[0][0]             
                                                                 sparse_emb_city[0][0]            
                                                                 sparse_emb_curclientversioncode[0
                                                                 sparse_emb_lastua[0][0]          
                                                                 sparse_emb_phonecountrycode[0][0]
__________________________________________________________________________________________________
no_mask_5 (NoMask)              (None, 1)            0           item_pop[0][0]                   
                                                                 singerLocalPop[0][0]             
                                                                 singerGlobalPop[0][0]            
                                                                 publicDays[0][0]                 
__________________________________________________________________________________________________
concatenate_3 (Concatenate)     (None, 1, 44)        0           no_mask_4[0][0]                  
                                                                 no_mask_4[1][0]                  
                                                                 no_mask_4[2][0]                  
                                                                 no_mask_4[3][0]                  
                                                                 no_mask_4[4][0]                  
                                                                 no_mask_4[5][0]                  
                                                                 no_mask_4[6][0]                  
                                                                 no_mask_4[7][0]                  
                                                                 no_mask_4[8][0]                  
                                                                 no_mask_4[9][0]                  
                                                                 no_mask_4[10][0]                 
__________________________________________________________________________________________________
concatenate_4 (Concatenate)     (None, 4)            0           no_mask_5[0][0]                  
                                                                 no_mask_5[1][0]                  
                                                                 no_mask_5[2][0]                  
                                                                 no_mask_5[3][0]                  
__________________________________________________________________________________________________
linear0sparse_emb_afid_index (E (None, 1, 1)         1240        afid_index[0][0]                 
__________________________________________________________________________________________________
linear0sparse_emb_itemId_index  (None, 1, 1)         17924       itemId_index[0][0]               
__________________________________________________________________________________________________
linear0sparse_emb_singerid_inde (None, 1, 1)         4025        singerid_index[0][0]             
__________________________________________________________________________________________________
linear0sparse_emb_singerCountry (None, 1, 1)         111         singerCountry_index[0][0]        
__________________________________________________________________________________________________
linear0sparse_emb_currentCountr (None, 1, 1)         24          currentCountry[0][0]             
__________________________________________________________________________________________________
linear0sparse_emb_ageLV (Embedd (None, 1, 1)         12          ageLV[0][0]                      
__________________________________________________________________________________________________
linear0sparse_emb_sex (Embeddin (None, 1, 1)         3           sex[0][0]                        
__________________________________________________________________________________________________
linear0sparse_emb_city (Embeddi (None, 1, 1)         78          city[0][0]                       
__________________________________________________________________________________________________
linear0sparse_emb_curclientvers (None, 1, 1)         101         curclientversioncode[0][0]       
__________________________________________________________________________________________________
linear0sparse_emb_lastua (Embed (None, 1, 1)         411         lastua[0][0]                     
__________________________________________________________________________________________________
linear0sparse_emb_phonecountryc (None, 1, 1)         18          phonecountrycode[0][0]           
__________________________________________________________________________________________________
flatten (Flatten)               (None, 44)           0           concatenate_3[0][0]              
__________________________________________________________________________________________________
flatten_1 (Flatten)             (None, 4)            0           concatenate_4[0][0]              
__________________________________________________________________________________________________
no_mask (NoMask)                (None, 1, 1)         0           linear0sparse_emb_afid_index[0][0
                                                                 linear0sparse_emb_itemId_index[0]
                                                                 linear0sparse_emb_singerid_index[
                                                                 linear0sparse_emb_singerCountry_i
                                                                 linear0sparse_emb_currentCountry[
                                                                 linear0sparse_emb_ageLV[0][0]    
                                                                 linear0sparse_emb_sex[0][0]      
                                                                 linear0sparse_emb_city[0][0]     
                                                                 linear0sparse_emb_curclientversio
                                                                 linear0sparse_emb_lastua[0][0]   
                                                                 linear0sparse_emb_phonecountrycod
__________________________________________________________________________________________________
no_mask_1 (NoMask)              (None, 1)            0           item_pop[0][0]                   
                                                                 singerLocalPop[0][0]             
                                                                 singerGlobalPop[0][0]            
                                                                 publicDays[0][0]                 
__________________________________________________________________________________________________
no_mask_6 (NoMask)              multiple             0           flatten[0][0]                    
                                                                 flatten_1[0][0]                  
__________________________________________________________________________________________________
concatenate (Concatenate)       (None, 1, 11)        0           no_mask[0][0]                    
                                                                 no_mask[1][0]                    
                                                                 no_mask[2][0]                    
                                                                 no_mask[3][0]                    
                                                                 no_mask[4][0]                    
                                                                 no_mask[5][0]                    
                                                                 no_mask[6][0]                    
                                                                 no_mask[7][0]                    
                                                                 no_mask[8][0]                    
                                                                 no_mask[9][0]                    
                                                                 no_mask[10][0]                   
__________________________________________________________________________________________________
concatenate_1 (Concatenate)     (None, 4)            0           no_mask_1[0][0]                  
                                                                 no_mask_1[1][0]                  
                                                                 no_mask_1[2][0]                  
                                                                 no_mask_1[3][0]                  
__________________________________________________________________________________________________
concatenate_5 (Concatenate)     (None, 48)           0           no_mask_6[0][0]                  
                                                                 no_mask_6[1][0]                  
__________________________________________________________________________________________________
no_mask_3 (NoMask)              (None, 1, 4)         0           sparse_emb_afid_index[0][0]      
                                                                 sparse_emb_itemId_index[0][0]    
                                                                 sparse_emb_singerid_index[0][0]  
                                                                 sparse_emb_singerCountry_index[0]
                                                                 sparse_emb_currentCountry[0][0]  
                                                                 sparse_emb_ageLV[0][0]           
                                                                 sparse_emb_sex[0][0]             
                                                                 sparse_emb_city[0][0]            
                                                                 sparse_emb_curclientversioncode[0
                                                                 sparse_emb_lastua[0][0]          
                                                                 sparse_emb_phonecountrycode[0][0]
__________________________________________________________________________________________________
linear (Linear)                 (None, 1)            4           concatenate[0][0]                
                                                                 concatenate_1[0][0]              
__________________________________________________________________________________________________
dnn (DNN)                       (None, 256)          78336       concatenate_5[0][0]              
__________________________________________________________________________________________________
concatenate_2 (Concatenate)     (None, 11, 4)        0           no_mask_3[0][0]                  
                                                                 no_mask_3[1][0]                  
                                                                 no_mask_3[2][0]                  
                                                                 no_mask_3[3][0]                  
                                                                 no_mask_3[4][0]                  
                                                                 no_mask_3[5][0]                  
                                                                 no_mask_3[6][0]                  
                                                                 no_mask_3[7][0]                  
                                                                 no_mask_3[8][0]                  
                                                                 no_mask_3[9][0]                  
                                                                 no_mask_3[10][0]                 
__________________________________________________________________________________________________
no_mask_2 (NoMask)              (None, 1)            0           linear[0][0]                     
__________________________________________________________________________________________________
dense (Dense)                   (None, 1)            256         dnn[0][0]                        
__________________________________________________________________________________________________
cin (CIN)                       (None, 192)          105856      concatenate_2[0][0]              
__________________________________________________________________________________________________
add (Add)                       (None, 1)            0           no_mask_2[0][0]                  
                                                                 dense[0][0]                      
__________________________________________________________________________________________________
dense_1 (Dense)                 (None, 1)            193         cin[0][0]                        
__________________________________________________________________________________________________
add_1 (Add)                     (None, 1)            0           add[0][0]                        
                                                                 dense_1[0][0]                    
__________________________________________________________________________________________________
prediction_layer (PredictionLay (None, 1)            1           add_1[0][0]                      
==================================================================================================
Total params: 304,381
Trainable params: 304,381
Non-trainable params: 0
__________________________________________________________________________________________________

**Comment by JWenBin** [comment]
Here is something about my model.summary():
```
Model: "model"
__________________________________________________________________________________________________
concatenate_4 (Concatenate)     (None, 4)            0           no_mask_5[0][0]                  
                                                                 no_mask_5[1][0]                  
                                                                 no_mask_5[2][0]                  
                                                                 no_mask_5[3][0]                  
__________________________________________________________________________________________________
.......     
__________________________________________________________________________________________________
flatten_1 (Flatten)             (None, 4)            0           concatenate_4[0][0]              
__________________________________________________________________________________________________
......

Here is something in saved_model.pb:
```
concatenate_4/concat/axis?
concatenate_4/concatConcatV2	inputs_11	inputs_12	inputs_13	inputs_14"concatenate_4/concat/axis:output:0*
```

I guess it case by this:
`tf.keras.layers.Concatenate(axis=axis)(inputs)`

**Comment by Craigacp** [comment]
What shape are your inputs, and what shape are the placeholders that you're feeding them to?

**Comment by JWenBin** [comment]
> 
> 
> What shape are your inputs, and what shape are the placeholders that you're feeding them to?

In order to analysis this error, I only keep 2 sparse features and retrain my model. Then reload it in scala project: 

```
val userid_index=TInt32.vectorOf(450)
val itemId_index=TInt32.vectorOf(6135) 
val z = session.runner()
  .feed("serving_default_uid_index", userid_index)
  .feed("serving_default_itemId_index", itemId_index)
  .fetch("StatefulPartitionedCall:0")
  .run()
  .get(0)
```
But the error message still exist:
```
Exception in thread "main" org.tensorflow.exceptions.TFInvalidArgumentException: ConcatOp : Expected concatenating dimensions in the range [-2, 2), but got 2
	 [[{{node model/concatenate_2/concat}}]]
	at org.tensorflow.internal.c_api.AbstractTF_Status.throwExceptionIfNotOK(AbstractTF_Status.java:87)
	at org.tensorflow.Session.run(Session.java:691)
	at org.tensorflow.Session.access$100(Session.java:72)
	at org.tensorflow.Session$Runner.runHelper(Session.java:381)
	at org.tensorflow.Session$Runner.run(Session.java:329)
```

**Comment by JWenBin** [comment]
I tried to use saved_model_cli to load and run my model too:
```
(TF2) C:\Users\lenovo>saved_model_cli run --dir F:/tmp/ml/output/20190729/TF/output/xDeepFM --tag_set serve --signature_def serving_default --input_exprs userid_index=np.array([[450]]).astype(np.int32);itemId_index=np.array([[6135]]).astype(np.int32);
2021-04-02 14:02:28.285380: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudart64_110.dll
2021-04-02 14:02:32.002765: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-04-02 14:02:32.011832: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library nvcuda.dll
2021-04-02 14:02:32.058377: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 0 with properties:
pciBusID: 0000:65:00.0 name: Quadro P400 computeCapability: 6.1
coreClock: 1.2525GHz coreCount: 2 deviceMemorySize: 2.00GiB deviceMemoryBandwidth: 29.88GiB/s
2021-04-02 14:02:32.083605: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudart64_110.dll
2021-04-02 14:02:32.112116: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cublas64_11.dll
2021-04-02 14:02:32.121792: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cublasLt64_11.dll
2021-04-02 14:02:32.139319: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cufft64_10.dll
2021-04-02 14:02:32.149954: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library curand64_10.dll
2021-04-02 14:02:32.165868: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cusolver64_10.dll
2021-04-02 14:02:32.180181: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cusparse64_11.dll
2021-04-02 14:02:32.190946: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudnn64_8.dll
2021-04-02 14:02:32.201736: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1862] Adding visible gpu devices: 0
2021-04-02 14:02:32.219704: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-04-02 14:02:32.247598: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 0 with properties:
pciBusID: 0000:65:00.0 name: Quadro P400 computeCapability: 6.1
coreClock: 1.2525GHz coreCount: 2 deviceMemorySize: 2.00GiB deviceMemoryBandwidth: 29.88GiB/s
2021-04-02 14:02:32.270262: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudart64_110.dll
2021-04-02 14:02:32.284601: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cublas64_11.dll
2021-04-02 14:02:32.294301: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cublasLt64_11.dll
2021-04-02 14:02:32.303395: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cufft64_10.dll
2021-04-02 14:02:32.315077: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library curand64_10.dll
2021-04-02 14:02:32.325374: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cusolver64_10.dll
2021-04-02 14:02:32.335132: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cusparse64_11.dll
2021-04-02 14:02:32.344842: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudnn64_8.dll
2021-04-02 14:02:32.355503: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1862] Adding visible gpu devices: 0
2021-04-02 14:02:33.437608: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1261] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-04-02 14:02:33.445822: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1267]      0
2021-04-02 14:02:33.454627: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1280] 0:   N
2021-04-02 14:02:33.461765: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1406] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 1344 MB memory) -> physical GPU (device: 0, name: Quadro P400, pci bus id: 0000:65:00.0, compute capability: 6.1)
2021-04-02 14:02:33.486249: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
WARNING:tensorflow:From d:\anaconda3\envs\tf2\lib\site-packages\tensorflow\python\tools\saved_model_cli.py:445: load (from tensorflow.python.saved_model.loader_impl) is deprecated and will be removed in a future version.
Instructions for updating:
This function will only be available through the v1 compatibility library as tf.compat.v1.saved_model.loader.load or tf.compat.v1.saved_model.load. There will be a new function for importing SavedModels in Tensorflow 2.0.
INFO:tensorflow:Restoring parameters from F:/tmp/ml/output/20190729/TF/output/xDeepFM\variables\variables
2021-04-02 14:02:33.813131: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:196] None of the MLIR optimization passes are enabled (registered 0 passes)
2021-04-02 14:02:34.345240: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cublas64_11.dll
2021-04-02 14:02:35.032044: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cublasLt64_11.dll
2021-04-02 14:02:35.046418: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudnn64_8.dll
2021-04-02 14:02:36.589842: I tensorflow/core/platform/windows/subprocess.cc:308] SubProcess ended with return code: 0

2021-04-02 14:02:36.746081: I tensorflow/core/platform/windows/subprocess.cc:308] SubProcess ended with return code: 0

Result for output key prediction_layer:
[[0.8332787]]

(TF2) C:\Users\lenovo>
```
We can see the result predict score=0.8332787, so our model file is right. But I still don't know the difference between saved_model_cli.py and TF-Java. Why my TF-Java0.3.1 could not run my model?

**Comment by JWenBin** [comment]
I tried to use saved_model_cli to load and run my model too:
```
(TF2) C:\Users\lenovo>saved_model_cli run --dir F:/tmp/ml/output/20190729/TF/output/xDeepFM --tag_set serve --signature_def serving_default --input_exprs userid_index=np.array([[450]]).astype(np.int32);itemId_index=np.array([[6135]]).astype(np.int32);
2021-04-02 14:02:28.285380: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudart64_110.dll
2021-04-02 14:02:32.002765: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-04-02 14:02:32.011832: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library nvcuda.dll
2021-04-02 14:02:32.058377: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 0 with properties:
pciBusID: 0000:65:00.0 name: Quadro P400 computeCapability: 6.1
coreClock: 1.2525GHz coreCount: 2 deviceMemorySize: 2.00GiB deviceMemoryBandwidth: 29.88GiB/s
2021-04-02 14:02:32.083605: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudart64_110.dll
2021-04-02 14:02:32.112116: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cublas64_11.dll
2021-04-02 14:02:32.121792: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cublasLt64_11.dll
2021-04-02 14:02:32.139319: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cufft64_10.dll
2021-04-02 14:02:32.149954: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library curand64_10.dll
2021-04-02 14:02:32.165868: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cusolver64_10.dll
2021-04-02 14:02:32.180181: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cusparse64_11.dll
2021-04-02 14:02:32.190946: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudnn64_8.dll
2021-04-02 14:02:32.201736: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1862] Adding visible gpu devices: 0
2021-04-02 14:02:32.219704: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-04-02 14:02:32.247598: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 0 with properties:
pciBusID: 0000:65:00.0 name: Quadro P400 computeCapability: 6.1
coreClock: 1.2525GHz coreCount: 2 deviceMemorySize: 2.00GiB deviceMemoryBandwidth: 29.88GiB/s
2021-04-02 14:02:32.270262: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudart64_110.dll
2021-04-02 14:02:32.284601: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cublas64_11.dll
2021-04-02 14:02:32.294301: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cublasLt64_11.dll
2021-04-02 14:02:32.303395: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cufft64_10.dll
2021-04-02 14:02:32.315077: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library curand64_10.dll
2021-04-02 14:02:32.325374: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cusolver64_10.dll
2021-04-02 14:02:32.335132: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cusparse64_11.dll
2021-04-02 14:02:32.344842: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudnn64_8.dll
2021-04-02 14:02:32.355503: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1862] Adding visible gpu devices: 0
2021-04-02 14:02:33.437608: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1261] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-04-02 14:02:33.445822: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1267]      0
2021-04-02 14:02:33.454627: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1280] 0:   N
2021-04-02 14:02:33.461765: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1406] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 1344 MB memory) -> physical GPU (device: 0, name: Quadro P400, pci bus id: 0000:65:00.0, compute capability: 6.1)
2021-04-02 14:02:33.486249: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
WARNING:tensorflow:From d:\anaconda3\envs\tf2\lib\site-packages\tensorflow\python\tools\saved_model_cli.py:445: load (from tensorflow.python.saved_model.loader_impl) is deprecated and will be removed in a future version.
Instructions for updating:
This function will only be available through the v1 compatibility library as tf.compat.v1.saved_model.loader.load or tf.compat.v1.saved_model.load. There will be a new function for importing SavedModels in Tensorflow 2.0.
INFO:tensorflow:Restoring parameters from F:/tmp/ml/output/20190729/TF/output/xDeepFM\variables\variables
2021-04-02 14:02:33.813131: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:196] None of the MLIR optimization passes are enabled (registered 0 passes)
2021-04-02 14:02:34.345240: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cublas64_11.dll
2021-04-02 14:02:35.032044: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cublasLt64_11.dll
2021-04-02 14:02:35.046418: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudnn64_8.dll
2021-04-02 14:02:36.589842: I tensorflow/core/platform/windows/subprocess.cc:308] SubProcess ended with return code: 0

2021-04-02 14:02:36.746081: I tensorflow/core/platform/windows/subprocess.cc:308] SubProcess ended with return code: 0

Result for output key prediction_layer:
[[0.8332787]]

(TF2) C:\Users\lenovo>
```
We can see the result predict score=0.8332787, so our model file is right. But I still don't know the difference between saved_model_cli.py and TF-Java. Why my TF-Java0.3.1 could not run my model?

**Comment by JWenBin** [comment]
Inspired by saved_model_cli, I changed my code of create tensor:
//    val itemId_index=TInt32.vectorOf(286)
    val itemId_index=TInt32.tensorOf(StdArrays.ndCopyOf(Array(Array(6135))) )
Everything is ok now! Thanks!

**Comment by JWenBin** [comment]
How can I cast a Tensor to TFloat32 like Tensor.toTFloat32()? Or get value form a Tensor like 'TFloat32.copyTo()/'? I haven't find Tensor.copyTo() in new version TF-Java.

**Comment by Craigacp** [comment]
The tensors returned by the `run` method are typed, so if the output should be a `TFloat32` then you can just cast it to that. You'll get a `ClassCastException` if it's the wrong type, but you should know what the type is from the graph. You can add operation that cast between tensor types.

Tensors are directly readable in the current version, so you can query them using the `get{Float,Double,...}(long... coordinates)` methods once they've been cast to the appropriate type.

**Comment by JWenBin** [comment]
> 
> 
> The tensors returned by the `run` method are typed, so if the output should be a `TFloat32` then you can just cast it to that. You'll get a `ClassCastException` if it's the wrong type, but you should know what the type is from the graph. You can add operation that cast between tensor types.
> 
> Tensors are directly readable in the current version, so you can query them using the `get{Float,Double,...}(long... coordinates)` methods once they've been cast to the appropriate type.

Thanks! I use 'asInstanceOf' to cast it to that. like this:

```
val resTensor: Tensor = session.runner()
      .feed("serving_default_afid_index", userid_index)
// other feed...
      .fetch("StatefulPartitionedCall:0")
      .run()
      .get(0)
val resultArray = ofDim[Float](2, 1)
StdArrays.copyFrom( resTensor.asInstanceOf[TFloat32], resultArray )
```
em...... Is there any better way to get tensor value to 'resultArray'?

**Comment by Craigacp** [comment]
It depends what you are doing. The tensor itself is directly readable, so you can access the values you need by using the `getFloat` or `getDouble` methods and supplying the necessary co-ordinates. Alternatively you can copy the result out into a Java array using the code that you posted.
