### ISSUE TITLE
java.lang.UnsatisfiedLinkError: no jnitensorflow in java.library.path for mkl-gpu (works for non-mkl gpu)

### ISSUE THREAD

**Issue by jxtps** [tensorflow/java#290]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): no
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Win10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.4.1 / 0.3.1
- CUDA/cuDNN version: 11.0.2 / 8.0.2
- GPU model and memory: Titan RTX, 24gb

**Describe the current behavior**
Using `tensorflow-core-platform-mkl-gpu` v 0.3.1 in Win10 with Java 8 results in: 
```
java.lang.UnsatisfiedLinkError: no jnitensorflow in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1860)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1683)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1300)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1123)
	at org.tensorflow.internal.c_api.global.tensorflow.<clinit>(tensorflow.java:12)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1190)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1139)
	at org.tensorflow.NativeLibrary.load(NativeLibrary.java:48)
	at org.tensorflow.TensorFlow.init(TensorFlow.java:111)
	at org.tensorflow.TensorFlow.<clinit>(TensorFlow.java:126)
	at org.tensorflow.SavedModelBundle.<clinit>(SavedModelBundle.java:438)
```

Using `tensorflow-core-platform-gpu` (i.e. non-`mkl`) v 0.3.1 works. 

**Describe the expected behavior**
Both versions should work. 

**Code to reproduce the issue**
Use existing sample program and switch the dependency to `tensorflow-core-platform-mkl-gpu` v 0.3.1

**Comment by saudet** [comment]
It's not currently possible to build TensorFlow with both CUDA and MKL enabled on Windows. There's apparently a way to work around that documented in Chinese here, but no one has taken the time to try it out:
 * https://blog.csdn.net/u012440550/article/details/113361176#t11

If you could take the time to report this bug upstream, we may be able to get engineers from Intel working on this! Thanks

**Comment by Craigacp** [comment]
Upstream MKL support got folded in to the native binary, and we're using those binaries now.
