### ISSUE TITLE
Simple Project Not Working

### ISSUE THREAD

**Issue by tomaspiaggio** [tensorflow/java#374]
# Host description
- **OS**: Windows 10
- **Memory**: 16GB
- **CPU**: Intel i7 8700
- **GPU**: Nvidia GeForece RTX 2080
- **Java Version**: 8

[Simple project to replicate the problem](https://github.com/tomaspiaggio/laughing-octo-eureka)

# Problem description

The main method is straight out of the docs [here](https://www.tensorflow.org/jvm/install#example_program). I can't seem to make it work. My main language of choice is Scala. I was trying to make it work in sbt and was getting a similar exception. From what I searched on the internet, it seems to be a JavaCPP error (missing `*-platform`). I don't think I'm doing anything wrong as I copied the example project. Please correct my if I'm wrong.

```java
Warning: Could not load Loader: java.lang.UnsatisfiedLinkError: no jnijavacpp in java.library.path
Exception in thread "main" java.lang.UnsatisfiedLinkError: no jnitensorflow in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1860)
	at java.lang.Runtime.loadLibrary0(Runtime.java:871)
	at java.lang.System.loadLibrary(System.java:1122)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1683)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1300)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1123)
	at org.tensorflow.internal.c_api.global.tensorflow.<clinit>(tensorflow.java:12)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1190)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1139)
	at org.tensorflow.NativeLibrary.load(NativeLibrary.java:48)
	at org.tensorflow.TensorFlow.init(TensorFlow.java:111)
	at org.tensorflow.TensorFlow.<clinit>(TensorFlow.java:126)
	at my.project.App.main(App.java:19)
Caused by: java.lang.UnsatisfiedLinkError: no tensorflow_cc in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1860)
	at java.lang.Runtime.loadLibrary0(Runtime.java:871)
	at java.lang.System.loadLibrary(System.java:1122)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1683)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1227)
	... 10 more
```

**Comment by tomaspiaggio** [comment]
I just tested the same code on my mac and it worked perfectly. Could there be an issue with Windows specifically?

**Comment by Craigacp** [comment]
Did Maven download `tensorflow-core-api-0.3.1-windows-x86_64.jar` to your local Maven cache? That jar should contain `jnitensorflow.dll` and `tensorflow_cc.dll`. It's available here - https://repo1.maven.org/maven2/org/tensorflow/tensorflow-core-api/0.3.1/.

**Comment by rnett** [comment]
Your project works fine for me, and I've been able to use tensorflow java in other projects, so this is likely something on your end.  Try removing the `~/.m2/org/tensorflow` directory maybe?  And make sure you're building and running through maven, not IntelliJ (see [this](https://www.jetbrains.com/help/idea/delegate-build-and-run-actions-to-maven.html#delegate_to_maven)).
