### ISSUE TITLE
SavedModelBundle problem loading in version 0.4.0

### ISSUE THREAD

**Issue by arianmaghsoudnia** [tensorflow/java#401]
**System information**

- OS Platform and Distribution: Linux Ubuntu 20.04 x64
- TensorFlow installed from: pip for Python 3.9; Maven for Java 
- TensorFlow version : 2.7.0 on Python; 0.4.0 on Java
- Java version : openjdk 11.0.11 2021-04-20
- Python version : 3.9
- CUDA/cuDNN version: cuda_11.5.r11.5/compiler.30411180_0
- GPU model and memory: Nvidia Geforce 960m

**Describe the current behavior**
I am using SavedModelBundle.load method to load a saved model from Python. Up to some days ago it worked fine but when I tested today, this exception was thrown:

> java.lang.UnsatisfiedLinkError: no jnitensorflow in java.library.path: /usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib

**Describe the expected behavior**
Return SavedModelBundle object.

**Code to reproduce the issue**
I used the 0.4.0-SNAPSHOT version so unfortunately I can not reproduce the working repo and check where things went wrong! 

**Other info / logs**
`
at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2429)
at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:818)
at java.base/java.lang.System.loadLibrary(System.java:1989)
at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1738)
at org.bytedeco.javacpp.Loader.load(Loader.java:1345)
at org.bytedeco.javacpp.Loader.load(Loader.java:1157)
at org.bytedeco.javacpp.Loader.load(Loader.java:1133)
at org.tensorflow.internal.c_api.global.tensorflow.<clinit>(tensorflow.java:12)
at java.base/java.lang.Class.forName0(Native Method)
at java.base/java.lang.Class.forName(Class.java:467)
at org.bytedeco.javacpp.Loader.load(Loader.java:1212)
at org.bytedeco.javacpp.Loader.load(Loader.java:1157)
at org.bytedeco.javacpp.Loader.load(Loader.java:1149)
at org.tensorflow.NativeLibrary.load(NativeLibrary.java:48)
at org.tensorflow.TensorFlow.<clinit>(TensorFlow.java:140)
at java.base/java.lang.Class.forName0(Native Method)
at java.base/java.lang.Class.forName(Class.java:375)
at org.tensorflow.SavedModelBundle.<clinit>(SavedModelBundle.java:651)
`

**Comment by arianmaghsoudnia** [comment]
Actually, I found the problem is not specifically related to SavedModelBundle; I faced it as it was the entry point to my code. Using any method of any classes traces back to this error.

**Comment by karllessard** [comment]
Hi @arianmaghsoudnia , so just to be clear, are you using the newly released 0.4.0 artifacts or the old 0.4.0-SNAPSHOTs?

Also can you post how you've set your dependencies to TF Java in your pom/gradle file?

**Comment by arianmaghsoudnia** [comment]
Initially I tried as the documentation say:
```xml
<dependency>
<groupId>org.tensorflow</groupId>
  <artifactId>tensorflow-core-api</artifactId>
  <version>0.4.0</version>
</dependency>
<dependency>
  <groupId>org.tensorflow</groupId>
  <artifactId>tensorflow-core-api</artifactId>
  <version>0.4.0</version>
  <classifier>linux-x86_64</classifier>
</dependency>
```
Which caused the aforementioned error.
Now I switched to:
```xml
      <dependency>
            <groupId>org.tensorflow</groupId>
            <artifactId>tensorflow-core-platform</artifactId>
            <version>0.4.0</version>
        </dependency>
```
So I checked the installed repository and found out that "ndarray:0.3.3", core-api:0.4.0 for all platforms, and core-platform:0.4 are installed. Please see the snip of it from my project library:
![image](https://user-images.githubusercontent.com/55542530/144637858-0f0c6cb1-ec9a-4371-95ec-29ad325abee8.png)

This caused the error to go away but another problem arose that I'm not sure is related to this issue. Now trying to load the model the program waits indefinitely without throwing any exceptions. I got the following thread dump log:
```"main@1" prio=5 tid=0x1 nid=NA runnable
java.lang.Thread.State: RUNNABLE
    at org.tensorflow.internal.c_api.global.tensorflow.TF_NewGraph(tensorflow.java:-1)
    at org.tensorflow.SavedModelBundle.load(SavedModelBundle.java:618)
    at org.tensorflow.SavedModelBundle.access$000(SavedModelBundle.java:67)
    at org.tensorflow.SavedModelBundle$Loader.load(SavedModelBundle.java:97)
    at org.tensorflow.SavedModelBundle.load(SavedModelBundle.java:357)
```
Indeed the simple process of creating a new Graph() triggers this behavior.

**Comment by arianmaghsoudnia** [comment]
I found the problem; It was the IntelliJ causing trouble! I tested directly using Maven CLI and also Eclipse and surprisingly the problem did not reproduce there. I did a clean install/ Invalidating cache/Reloading project of Intellij and none of them were enough to make the problem go away. 
It is not a relevant issue of Tensorflow anymore but still, I provided a repo if you want to take a look at it. Maybe you can also test if you can reproduce it using IntelliJ so we can report them?
 
Using Intellij as IDE, after starting a KafkaStreams topology that contains KTable methods, Tensorflow waits indefinitely at  
org.tensorflow.internal.c_api.global.tensorflow.TF_NewGraph
.

Code to reproduce the issue
Please take a look at this minimal [repo](https://github.com/arianmaghsoudnia/TensorFlow-KafkaTestTopology).

Other info/logs:
IntelliJ Version : IntelliJ IDEA 2021.3

**Comment by karllessard** [comment]
Aaah of course yes, I often have this problem with IntelliJ as well. What works often for me (but not always) is to do a `mvn install` from the CLI first, then I reimport the Maven settings from IntelliJ and rebuild. 

But be aware that often after importing Maven settings in IntelliJ, it tries to bind to the `OperatorProcessor` annotation processor, which it couldn't find for some obscure reasons. So before rebuilding, you might want to remove that processor from your Settings as follow:
![image](https://user-images.githubusercontent.com/10109534/145267607-fc5c8a05-5913-4f3f-aa39-1b750974a6be.png)

**Comment by rnett** [comment]
@arianmaghsoudnia are you delegating the build/run action to maven?  Or trying to use IntelliJ's built in build system?  I usually have much more success with delegating to maven, however I checked out your project and both work fine for me.  It's probably a configuration issue, can you try re-cloning your project somewhere else and trying there?

**Comment by arianmaghsoudnia** [comment]
Thank you, guys!

@karllessard  The processor FQ Name list of mine is clear, to begin with.

@rnett  Recloning the project did not solve the issue;  I am using native IntelliJ IDEA builder to build but after your response, I started delegating it to the Maven and it did not work first. However, when I additionally replaced the Maven home path from Bundled(Maven 3) to the latest one I directly downloaded from Apache (Version: 3.8.4), the issue was resolved.
