### ISSUE TITLE
NullPointerException when calling matrixDiagV3

### ISSUE THREAD

**Issue by frankfliu** [tensorflow/java#406]
The following code works fine with 0.3.1, but now I get NPE in 0.4.0:

```
        EagerSession eagerSession = EagerSession.options().async(true).build();
        Ops tf = Ops.create(eagerSession);
        Operand<TFloat32> diagonal = tf.fill(tf.constant(new long[]{2}), tf.constant(1f));
        Operand<TFloat32> value = tf.fill(tf.constant(new long[]{1}), tf.constant(0f));

        Operand<TFloat32> output =
                tf.linalg.matrixDiagV3(
                        diagonal, tf.constant(0), tf.constant(2), tf.constant(2), value);
        Tensor tensor = output.asTensor(); // exception here
```

I got exception on both macOS and Linux.

```
java.lang.NullPointerException
	at org.tensorflow.EagerOperation.resolveTensorHandle(EagerOperation.java:193)
	at org.tensorflow.EagerOperation.resolveTensor(EagerOperation.java:166)
	at org.tensorflow.EagerOperation.tensor(EagerOperation.java:152)
	at org.tensorflow.Output.asTensor(Output.java:97)
	at org.tensorflow.Operand.asTensor(Operand.java:65)
```

**Comment by frankfliu** [comment]
@karllessard 

You are absolutely correct, padding should be a scalar. I think earlier version didn't enforce that.

But the NPE is bug in the code. I will create a PR to address that.
