### ISSUE TITLE
I wanna create shape(3,3,3) ones tensor ,but meet error ,does we only support reshape the ones tensor to multi shape?

### ISSUE THREAD

**Issue by mullerhai** [tensorflow/java#423]
Hi :
     I  want to create shape (3,3,3 ) ones or zeros tensor ,but why  meet error, if  the operation not correct for me ?

``` jvm scala 
import org.tensorflow.ndarray.{FloatNdArray, IntNdArray, Shape}
import org.tensorflow.{EagerSession, Graph, Operand, Session}
import org.tensorflow.op.Ops
//import org.tensorflow.op.core.Shape
import org.tensorflow.types.{TBool, TFloat32, TFloat64, TInt32}
import org.tensorflow.types.family.TFloating

    val shapez  =Shape.of(3,3,3)
    val tensorShz = TInt32.tensorOf(shapez)
    val shzz = tf.constant(tensorShz)
    val onesz= tf.ones(shzz,classOf[TInt32] )

```

the error console

```
Exception in thread "main" org.tensorflow.exceptions.TFInvalidArgumentException: dims must represent a vector, got shape [3,3,3]
	at org.tensorflow.internal.c_api.AbstractTF_Status.throwExceptionIfNotOK(AbstractTF_Status.java:87)
	at org.tensorflow.EagerOperationBuilder.execute(EagerOperationBuilder.java:314)
	at org.tensorflow.EagerOperationBuilder.build(EagerOperationBuilder.java:77)
	at org.tensorflow.EagerOperationBuilder.build(EagerOperationBuilder.java:64)
	at org.tensorflow.op.core.Fill.create(Fill.java:98)
	at org.tensorflow.op.core.Ones.create(Ones.java:58)
	at org.tensorflow.op.Ops.ones(Ops.java:3700)

```

**Comment by rnett** [comment]
`tensorOf` creates an uninitialized tensor with that shape, it does not turn the shape into a tensor of `[3, 3, 3]`.  You want something like `tf.ones(tf.array(3, 3, 3), classOf[TInt32])`.

**Comment by mullerhai** [comment]
> `tensorOf` creates an uninitialized tensor with that shape, it does not turn the shape into a tensor with values `[3, 3, 3]`. You want something like `tf.ones(tf.array(3, 3, 3), classOf[TInt32])`.

you are right, it's work,thanks
