### ISSUE TITLE
Tensorflow 0.4.0 docs say it should be compatible with JAva 8 but it is not

### ISSUE THREAD

**Issue by carlosuc3m** [tensorflow/java#490]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04 x86\_64): Windows x86_64, windows 10
- TensorFlow installed from (source or binary): binary (maven)
- TensorFlow version: 2.7.0 (Tf Java 0.4.0)
- Java version (i.e., the output of `java -version`): 1.8.0_271 (Java 8)
- Installed from Maven Central?: NO, downloaded from maven link directly
- CUDA/cuDNN version: No cuda
- GPU model and memory: NO gpu

**Describe the problem**

I am trying to load a JAva model using the TF JAva API 0.4.0 for Tf 2.7.0 but I encounter an error saying that it has been compiled for Java 11 and higher only (I am using JAva 8)

**Provide the exact sequence of commands / steps that you executed before running into the problem**

The error happens when I am trying to load with reflection:
```
Class< ? > c = engineClassloader.loadClass( className );
c.newInstance();
```
a class that uses the Tf2 0.4.0 Java dependencies. 
The class that I want to load is: https://github.com/bioimage-io/tensorflow-2-java-interface/blob/main/src/main/java/io/bioimage/modelrunner/tensorflow/v2/api030/Tensorflow2Interface.java

And I am loading the classes on a URLClassloader

**Any other info / logs**

This is the error:
```
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/tensorflow/ndarray/Shaped has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
```

**Comment by carlosuc3m** [comment]
Solved I was using the wrong NDArray version.
Sorry for the inconveninece!
